'use client';
import { useState } from 'react';
import { ArrowUpRight, FlaskConical, Plug, Radio, ShieldCheck } from 'lucide-react';
import { useWorkspace } from './workspace-context';
import type { MarketSnapshot } from '../domain/models';
import { pct, time, usd } from './format';
export function Connections() {
  const { state, busy, mutate, request } = useWorkspace();
  const [markets,setMarkets] = useState<MarketSnapshot[]>([]); const [loading,setLoading] = useState(false); const [error,setError] = useState<string | null>(null);
  async function loadMarkets() { setLoading(true); setError(null); try { const result = await request<{snapshots:MarketSnapshot[]}>({ command:'markets' }); setMarkets(result.snapshots); } catch(e) { setMarkets([]); setError(e instanceof Error ? e.message : 'Market data unavailable'); } finally { setLoading(false); } }
  return <><div className="page-heading"><div><div className="eyebrow">BINANCE-NATIVE BY DESIGN</div><h1>Know where your data comes from.</h1><p>Clear sources, limited permissions, and no hidden fallback data.</p></div></div><div className="two-column"><section className="panel connection-card"><span className="connection-icon"><FlaskConical size={22}/></span><h2>Wardyn demo</h2><span className="status">{state?.portfolio.source === 'demo' ? 'ACTIVE' : 'AVAILABLE'}</span><p className="inline-note">A complete simulated portfolio with five market scenarios, policy checks, approvals, and receipts. No keys or funds required.</p><button className="button secondary" disabled={busy} onClick={() => void mutate({ command:'scenario',scenario:'balanced' })}>Start a fresh demo</button></section><section className="panel connection-card"><span className="connection-icon"><Plug size={22}/></span><h2>Binance Skills Hub · CLI</h2><span className="status">{state?.portfolio.source === 'binance-cli' ? 'CONNECTED · READ ONLY' : 'LOCAL SETUP REQUIRED'}</span><p className="inline-note">Read balances, tickers, and candles through Binance’s official CLI. Install and authorize the CLI on this server, then enable account reads.</p><button className="button primary" disabled={busy} onClick={() => void mutate({ command:'connect' })}>Load Binance account</button><p className="inline-note">Local installation only. No live trading adapter is enabled.</p></section><section className="panel connection-card"><span className="connection-icon"><Radio size={22}/></span><h2>Public Binance market data</h2><p>Fetch current BTC, BNB, and SOL prices from official public REST endpoints. This preview does not connect or change your portfolio.</p><button className="button secondary" disabled={loading} onClick={() => void loadMarkets()}>{loading ? 'Fetching…' : 'Check live markets'}</button>{error && <p role="alert" className="negative inline-note">{error}</p>}{markets.map(m => <div className="effect-row section-gap" key={m.asset}><span>{m.asset} · {time(m.observedAt)}</span><strong>{usd(m.priceUsdt)} · {pct(m.change24hPct)}</strong></div>)}</section><section className="panel connection-card"><span className="connection-icon"><ShieldCheck size={22}/></span><h2>Binance MCP</h2><span className="subtle-tag">DISCOVERY UTILITY · NOT CONNECTED</span><p className="inline-note">The repository includes a tool-schema discovery utility for Binance’s documented MCP endpoint. OAuth connection and MCP trading are not implemented. Wardyn’s implemented Agent OS route uses the official Skills Hub CLI.</p><a className="button secondary" href="https://developers.binance.com/en/docs/agent-native/mcp-server/agentic" target="_blank" rel="noreferrer">Official MCP documentation<ArrowUpRight size={15}/></a></section></div></>;
}
