'use client';
import Link from 'next/link';
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check, Clock3, Play, ScanLine, ShieldCheck, Wallet } from 'lucide-react';
import { useState } from 'react';
import { useWorkspace } from './workspace-context';
import { amount, assetNames, pct, time, usd } from './format';
import { scenarios, type Scenario } from '../features/demo/provider';
import { assessRisk, evaluatePolicy } from '../domain/evaluate';
export function ScenarioControl() {
  const { busy, mutate } = useWorkspace(); const [selected, setSelected] = useState<Scenario>('concentration');
  return <div className="scenario-control"><label className="sr-only" htmlFor="scenario">Demo scenario</label><select id="scenario" value={selected} onChange={e => setSelected(e.target.value as Scenario)}>{Object.entries(scenarios).map(([key, s]) => <option key={key} value={key}>{s.name}</option>)}</select><button className="button primary" disabled={busy} onClick={() => void mutate({ command: 'scenario', scenario: selected })}><Play size={15}/>{busy ? 'Running…' : 'Run demo scenario'}</button></div>;
}
export function Dashboard() {
  const { state, busy, mutate } = useWorkspace(); if (!state) return null;
  const risk = assessRisk(state.portfolio, state.policy); const unresolved = evaluatePolicy(state.portfolio, state.policy).length > 0;
  const pending = state.receipts.filter(r => r.status === 'PENDING'); const featured = pending[0];
  return <><div className="page-heading"><div><div className="eyebrow">POSITION INTELLIGENCE</div><h1>Your portfolio. Under watch.</h1><p>A calmer way to manage what you already own.</p></div><button className="button secondary" disabled={busy} onClick={() => void mutate({ command: 'scan' })}><ScanLine size={16}/>Scan now</button></div><div className="watch-strip"><span><span className="live-dot"/>{state.monitoring ? 'Wardyn is watching' : 'Ready when you are'}</span><span>{state.portfolio.positions.length} positions · Last scan {time(state.runs[0].startedAt)}</span><Link href="/workspace/watch">View activity <ArrowRight size={14}/></Link></div><section className="metrics"><Metric label="Portfolio value" value={usd(state.portfolio.totalValueUsdt)} detail="Valued in USDT" icon={<Wallet size={17}/>}/><Metric label="Wardyn risk" value={risk.level.charAt(0) + risk.level.slice(1).toLowerCase()} detail={`${risk.score}/100 · Transparent rule-based score`} icon={<ShieldCheck size={17}/>} tone={risk.level.toLowerCase()}/><Metric label="Stable reserve" value={pct(state.portfolio.stableReservePct)} detail={`${state.policy.minStableReservePct}% minimum in your policy`} icon={<ArrowDownRight size={17}/>}/><Metric label="Needs attention" value={String(pending.length).padStart(2, '0')} detail={pending.length ? 'Your approval is required' : 'No actions awaiting approval'} icon={<Clock3 size={17}/>}/></section><div className="dashboard-grid"><div className="main-column"><section className="panel allocation-panel"><div className="panel-heading"><div><h2>Portfolio allocation</h2><p>Balance is a policy, not a guess.</p></div><span className="subtle-tag">{state.portfolio.source === 'demo' ? 'SIMULATED PORTFOLIO' : 'BINANCE ACCOUNT'}</span></div><div className="allocation-bar">{state.portfolio.positions.map(p => <div className={`asset-bg ${p.asset}`} key={p.asset} style={{ width: `${p.allocationPct}%` }} title={`${p.asset} ${pct(p.allocationPct)}`}/>)}</div><div className="allocation-legend">{state.portfolio.positions.map(p => <div key={p.asset}><span className={`asset-dot ${p.asset}`}/><span>{p.asset}</span><strong>{pct(p.allocationPct)}</strong></div>)}</div></section><section className="panel positions-panel"><div className="panel-heading"><div><h2>Your positions</h2><p>Every position has a plan.</p></div><span className="subtle-tag">SPOT</span></div><div className="table-scroll"><table><thead><tr><th>Asset</th><th>Value / Balance</th><th>Allocation</th><th>Unrealized PnL</th><th>Wardyn status</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{state.portfolio.positions.map(p => {
    const intervention = pending.find(r => r.decision.asset === p.asset); const decision = state.runs[0]?.decisions.find(d => d.asset === p.asset);
    return <tr key={p.asset}><td><Link href={`/workspace/positions/${p.asset}`} className="asset-cell"><span className={`asset-icon ${p.asset}`}>{p.asset === 'BTC' ? '₿' : p.asset === 'SOL' ? '≋' : p.asset === 'BNB' ? '◇' : '₮'}</span><span><strong>{p.asset}</strong><small>{assetNames[p.asset]}</small></span></Link></td><td><strong>{usd(p.valueUsdt)}</strong><small>{amount(p.quantity)} {p.asset}</small></td><td>{pct(p.allocationPct)}<span className="mini-track"><span className={`asset-bg ${p.asset}`} style={{ width: `${p.allocationPct}%` }}/></span></td><td className={(p.pnlPct ?? 0) >= 0 ? 'positive' : 'negative'}>{p.pnlPct === null ? 'Unknown' : `${p.pnlPct >= 0 ? '+' : ''}${pct(p.pnlPct)}`}<small>{p.pnlUsdt === null ? 'Entry unavailable' : usd(p.pnlUsdt)}</small></td><td><span className={`status ${intervention ? 'attention' : ''}`}>{intervention ? 'ACTION REQUIRED' : decision?.cooldown ? 'COOLDOWN' : 'HEALTHY'}</span></td><td><Link href={`/workspace/positions/${p.asset}`} aria-label={`View ${p.asset} details`}><ArrowUpRight size={17}/></Link></td></tr>;
  })}</tbody></table></div></section><section className="demo-panel"><div><span className="eyebrow">PUT WARDYN TO WORK</span><h3>A change in the market. A measured response.</h3><p>Run a scenario through the same policy engine. All actions use simulated funds.</p></div><ScenarioControl/></section></div><aside className="right-column"><section className={`decision-preview panel ${featured ? 'has-action' : ''}`}><div className="panel-heading"><span className="eyebrow">WARDYN DECISION</span><ShieldCheck size={22}/></div><span className={`decision-word ${featured ? featured.decision.decision.toLowerCase() : 'hold'}`}>{featured?.decision.decision ?? 'HOLD'}</span><h2>{featured ? `${featured.decision.asset} needs a measured adjustment.` : 'Sometimes, the right move is no move.'}</h2><p>{featured?.decision.reasons[0] ?? (unresolved ? 'A policy threshold remains breached. Review the latest decision for cooldown or action-size limits before another intervention.' : state.runs[0]?.decisions[0]?.reasons[0] ?? 'No intervention is currently proposed.')}</p>{featured ? <><div className="decision-facts"><div><span>Proposed reduction</span><strong>{pct(featured.decision.trade!.positionPct)}</strong></div><div><span>Estimated proceeds</span><strong>{usd(featured.decision.trade!.estimatedProceedsUsdt)}</strong></div></div><Link className="button primary full" href={`/workspace/positions/${featured.decision.asset}`}>Review decision<ArrowRight size={16}/></Link><small className="center-note">Nothing moves without your approval.</small></> : <div className="calm-mark"><Check size={18}/>{unresolved ? 'Review remaining policy triggers' : 'No intervention proposed'}</div>}</section><section className="panel policy-summary"><div className="panel-heading"><h2>Your guardrails</h2><Link href="/workspace/policy"><ArrowUpRight size={17}/></Link></div><div className="rule-line"><span>Max asset allocation</span><strong>{state.policy.maxAssetAllocationPct}%</strong></div><div className="rule-line"><span>Minimum stable reserve</span><strong>{state.policy.minStableReservePct}%</strong></div><div className="rule-line"><span>Peak drawdown limit</span><strong>{state.policy.maxPositionDrawdownPct}%</strong></div><div className="rule-line"><span>Profit strategy</span><strong>{state.policy.profitStrategy === 'scale_out' ? 'Scale out' : 'Hold'}</strong></div><div className="policy-footer"><ShieldCheck size={14}/>{state.policyConfirmed ? 'Your confirmed policy' : 'Demo policy · review to personalize'}</div></section></aside></div></>;
}
function Metric({ label, value, detail, icon, tone = '' }: { label: string; value: string; detail: string; icon: React.ReactNode; tone?: string }) { return <div className={`metric ${tone}`}><div className="metric-label">{label}{icon}</div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div></div>; }
